pretrained_model_name_or_path: stabilityai/stable-diffusion-2-1-base
revision: null
variant: null
tokenizer_name: null
instance_data_dir: /data/disney
class_data_dir: /data/person
instance_prompt: "photo of disney person"
class_prompt: "photo of a person"
validation_prompt: "photo of disney person"
num_validation_images: 4
validation_epochs: 1
validation_steps: 100
num_inference_steps: 30
with_prior_preservation: true
prior_loss_weight: 1.0
num_class_images: 1000
output_dir: lora-dreambooth-model
seed: 1337
resolution: 512
center_crop: false
train_text_encoder: true
train_batch_size: 4
sample_batch_size: 4
num_train_epochs: 1
max_train_steps: 9000
checkpointing_steps: 500
checkpoints_total_limit: null
resume_from_checkpoint: lora-dreambooth-model/checkpoint-4000
gradient_accumulation_steps: 1
gradient_checkpointing: false
learning_rate: 5e-4
scale_lr: false
lr_scheduler: constant
lr_warmup_steps: 500
lr_num_cycles: 1
lr_power: 1.0
dataloader_num_workers: 8
use_8bit_adam: true
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 0.01
adam_epsilon: 1.0e-08
max_grad_norm: 1.0
push_to_hub: false
hub_token: null
hub_model_id: null
logging_dir: logs
allow_tf32: false
report_to: wandb
mixed_precision: "fp16"
prior_generation_precision: null
local_rank: -1
enable_xformers_memory_efficient_attention: false
pre_compute_text_embeddings: false
tokenizer_max_length: null
text_encoder_use_attention_mask: false
validation_images: null
class_labels_conditioning: null
rank: 4
