#!/bin/bash

python train_dreambooth.py \
    --pretrained_model_name_or_path="runwayml/stable-diffusion-v1-5" \
    --revision="main" \
    --variant="fp16" \
    --instance_data_dir="/data/disney" \
    --class_data_dir="/data/artwork" \
    --instance_prompt="disney style" \
    --class_prompt= "artwork style" \
    --with_prior_preservation \
    --num_class_images=1000 \
    --prior_loss_weight=1.0 \
    --output_dir="dreambooth" \
    --seed=42 \
    --resolution=512 \
    --center_crop \
    --train_text_encoder \
    --train_batch_size=4 \
    --sample_batch_size=4 \
    --num_train_epochs=1 \
    --num_train_steps=10000 \
    --checkpointing_steps=500 \
    --gradient_accumulation_steps=1 \
    --learning_rate=1e-6 \
    --lr_scheduler="constant" \
    --lr_warmup_steps=0 \
    --use_8bit_adam \
    --dataloader_num_workers=8 \
    --adam_beta1=0.9 \
    --adam_beta2=0.999 \
    --adam_weight_decay=1e-2 \
    --adam_epsilon=1e-08 \
    --max_grad_norm=1.0 \
    --hub_model_id="cartoonify" \
    --logging_dir="logs" \
    --validation_steps=1000 \
    --mixed_precision="fp16" \
    --prior_generation_precision="fp16" \
    --snr_gamma=5.0 \
    --validation_scheduler="PNDMScheduler"
